# Generated by Django 6.0.1 on 2026-01-24 21:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('alternate_phone', models.CharField(blank=True, help_text='Alternate contact number', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Primary email (if different from user email)', max_length=254)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], max_length=20)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('id_number', models.CharField(blank=True, help_text='National ID / Passport Number', max_length=50)),
                ('marital_status', models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], max_length=20)),
                ('address_line_1', models.CharField(blank=True, help_text='Street address', max_length=255)),
                ('address_line_2', models.CharField(blank=True, help_text='Apartment, suite, etc.', max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state_province', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, default='Singapore', max_length=100)),
                ('education', models.JSONField(default=list, help_text='List of education: [{"institution": "...", "degree": "...", "field": "...", "start_year": "...", "end_year": "...", "gpa": "...", "honors": "..."}]')),
                ('experience', models.JSONField(default=list, help_text='List of work experience: [{"company": "...", "position": "...", "start_date": "...", "end_date": "...", "current": false, "responsibilities": "...", "achievements": "..."}]')),
                ('languages', models.JSONField(default=list, help_text='Languages: [{"language": "...", "proficiency": "Native/Fluent/Intermediate/Basic"}]')),
                ('certifications', models.JSONField(default=list, help_text='Certifications: [{"name": "...", "issuing_organization": "...", "issue_date": "...", "expiry_date": "...", "credential_id": "..."}]')),
                ('references', models.JSONField(default=list, help_text='References: [{"name": "...", "position": "...", "company": "...", "email": "...", "phone": "..."}]')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_relationship', models.CharField(blank=True, help_text='Relationship to applicant', max_length=50)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_email', models.EmailField(blank=True, max_length=254)),
                ('professional_summary', models.TextField(blank=True, help_text='Professional summary / About yourself')),
                ('cover_letter', models.TextField(blank=True, help_text='Cover letter / Personal statement')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('github_url', models.URLField(blank=True, help_text='GitHub profile URL')),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter/X profile URL')),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook profile URL')),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL')),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube channel URL')),
                ('behance_url', models.URLField(blank=True, help_text='Behance portfolio URL')),
                ('dribbble_url', models.URLField(blank=True, help_text='Dribbble portfolio URL')),
                ('medium_url', models.URLField(blank=True, help_text='Medium profile URL')),
                ('stackoverflow_url', models.URLField(blank=True, help_text='Stack Overflow profile URL')),
                ('portfolio_url', models.URLField(blank=True, help_text='Portfolio / Personal website URL')),
                ('projects', models.JSONField(blank=True, default=list, help_text='List of projects: [{"name": "...", "description": "...", "technologies": "...", "url": "...", "start_date": "...", "end_date": "...", "current": false}]')),
                ('availability_date', models.DateField(blank=True, help_text='Earliest available start date', null=True)),
                ('current_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Current salary (if applicable)', max_digits=10, null=True)),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Expected salary range', max_digits=10, null=True)),
                ('notice_period', models.CharField(blank=True, help_text='Notice period (e.g., "2 weeks", "1 month")', max_length=50)),
                ('additional_info', models.JSONField(blank=True, default=dict, help_text='Additional flexible information as JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skills', models.ManyToManyField(blank=True, related_name='applicant_profiles', to='jobs.skill')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'APPLICANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='applicant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Applicant Profile',
                'verbose_name_plural': 'Applicant Profiles',
                'db_table': 'applicant_profiles',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicantProfileDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CV', 'Curriculum Vitae / Resume'), ('BACHELORS_DEGREE', "Bachelor's Degree Certificate"), ('MASTERS_DEGREE', "Master's Degree Certificate"), ('DOCTORATE_DEGREE', 'Doctorate Degree Certificate'), ('DIPLOMA', 'Diploma Certificate'), ('TRANSCRIPT', 'Academic Transcript'), ('CERTIFICATE', 'Professional Certificate'), ('COVER_LETTER', 'Cover Letter'), ('ID_COPY', 'ID Copy / Passport'), ('REFERENCE_LETTER', 'Reference Letter'), ('PORTFOLIO', 'Portfolio'), ('OTHER', 'Other')], default='CV', max_length=50)),
                ('file', models.FileField(upload_to='applicant_documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('description', models.CharField(blank=True, help_text='Optional description', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('applicant_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.applicantprofile')),
            ],
            options={
                'verbose_name': 'Applicant Profile Document',
                'verbose_name_plural': 'Applicant Profile Documents',
                'db_table': 'applicant_profile_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_snapshot', models.JSONField(help_text='Complete snapshot of applicant profile at time of submission')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('SHORTLISTED', 'Shortlisted'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20)),
                ('ai_score', models.FloatField(blank=True, help_text='AI-generated score (0-100) for shortlisting', null=True)),
                ('ai_ranking', models.IntegerField(blank=True, help_text='Ranking position after AI shortlisting', null=True)),
                ('ai_explanation', models.TextField(blank=True, help_text='AI explanation for the score/ranking')),
                ('ai_shortlisted_at', models.DateTimeField(blank=True, help_text='Timestamp when AI shortlisting was performed', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job_advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobadvert')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'db_table': 'applications',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CV', 'Curriculum Vitae'), ('CERTIFICATE', 'Certificate'), ('TRANSCRIPT', 'Transcript'), ('COVER_LETTER', 'Cover Letter'), ('OTHER', 'Other')], default='CV', max_length=50)),
                ('file', models.FileField(upload_to='application_documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application')),
            ],
            options={
                'verbose_name': 'Application Document',
                'verbose_name_plural': 'Application Documents',
                'db_table': 'application_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='applicantprofile',
            index=models.Index(fields=['phone_number'], name='applicant_p_phone_n_cab647_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantprofile',
            index=models.Index(fields=['city', 'country'], name='applicant_p_city_a193ac_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantprofiledocument',
            index=models.Index(fields=['applicant_profile', 'document_type'], name='applicant_p_applica_928f83_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applicant', 'status'], name='application_applica_e9ee09_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job_advert', 'status'], name='application_job_adv_87cb2f_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', 'ai_ranking'], name='application_status_f97bda_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['submitted_at'], name='application_submitt_f3e3d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('applicant', 'job_advert')},
        ),
        migrations.AddIndex(
            model_name='applicationdocument',
            index=models.Index(fields=['application', 'document_type'], name='application_applica_051737_idx'),
        ),
    ]
