# Generated by Django 4.2.7 on 2026-01-13 08:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_snapshot', models.JSONField(help_text='Complete snapshot of applicant profile at time of submission')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('SHORTLISTED', 'Shortlisted'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20)),
                ('ai_score', models.FloatField(blank=True, help_text='AI-generated score (0-100) for shortlisting', null=True)),
                ('ai_ranking', models.IntegerField(blank=True, help_text='Ranking position after AI shortlisting', null=True)),
                ('ai_explanation', models.TextField(blank=True, help_text='AI explanation for the score/ranking')),
                ('ai_shortlisted_at', models.DateTimeField(blank=True, help_text='Timestamp when AI shortlisting was performed', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job_advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobadvert')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'db_table': 'applications',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('education', models.JSONField(default=list, help_text='List of education entries: [{"institution": "...", "degree": "...", "year": "..."}]')),
                ('experience', models.JSONField(default=list, help_text='List of work experience: [{"company": "...", "position": "...", "duration": "..."}]')),
                ('cover_letter', models.TextField(blank=True)),
                ('additional_info', models.JSONField(blank=True, default=dict, help_text='Additional flexible information as JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skills', models.ManyToManyField(blank=True, related_name='applicant_profiles', to='jobs.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Applicant Profile',
                'verbose_name_plural': 'Applicant Profiles',
                'db_table': 'applicant_profiles',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CV', 'Curriculum Vitae'), ('CERTIFICATE', 'Certificate'), ('TRANSCRIPT', 'Transcript'), ('COVER_LETTER', 'Cover Letter'), ('OTHER', 'Other')], default='CV', max_length=50)),
                ('file', models.FileField(upload_to='application_documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application')),
            ],
            options={
                'verbose_name': 'Application Document',
                'verbose_name_plural': 'Application Documents',
                'db_table': 'application_documents',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['application', 'document_type'], name='application_applica_051737_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applicant', 'status'], name='application_applica_e9ee09_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job_advert', 'status'], name='application_job_adv_87cb2f_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', 'ai_ranking'], name='application_status_f97bda_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['submitted_at'], name='application_submitt_f3e3d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('applicant', 'job_advert')},
        ),
    ]
