# Generated by Django 6.0.1 on 2026-01-24 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='profile_snapshot',
        ),
        migrations.CreateModel(
            name='ApplicationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True, help_text='Full address as submitted')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('education', models.JSONField(default=list, help_text='List of education: [{"institution": "...", "degree": "...", "field": "...", "start_year": "...", "end_year": "...", "gpa": "...", "honors": "..."}]')),
                ('experience', models.JSONField(default=list, help_text='List of work experience: [{"company": "...", "position": "...", "start_date": "...", "end_date": "...", "current": false, "responsibilities": "...", "achievements": "..."}]')),
                ('skills', models.TextField(blank=True, help_text='Skills separated by semicolons (;)')),
                ('cover_letter', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application_data', to='applications.application')),
            ],
            options={
                'verbose_name': 'Application Data',
                'verbose_name_plural': 'Application Data',
                'db_table': 'application_data',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number'], name='application_phone_n_e93d28_idx'), models.Index(fields=['email'], name='application_email_cdaa97_idx')],
            },
        ),
    ]
