# Generated by Django 4.2.7 on 2026-01-13 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'APPLICANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='applicant_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
