# Generated by Django 4.2.7 on 2026-01-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_applicantprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='address_line_1',
            field=models.CharField(blank=True, help_text='Street address', max_length=255),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='address_line_2',
            field=models.CharField(blank=True, help_text='Apartment, suite, etc.', max_length=255),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='alternate_phone',
            field=models.CharField(blank=True, help_text='Alternate contact number', max_length=20),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='availability_date',
            field=models.DateField(blank=True, help_text='Earliest available start date', null=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='certifications',
            field=models.JSONField(default=list, help_text='Certifications: [{"name": "...", "issuing_organization": "...", "issue_date": "...", "expiry_date": "...", "credential_id": "..."}]'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='country',
            field=models.CharField(blank=True, default='Singapore', max_length=100),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='current_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current salary (if applicable)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='email',
            field=models.EmailField(blank=True, help_text='Primary email (if different from user email)', max_length=254),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='emergency_contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, help_text='Relationship to applicant', max_length=50),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='expected_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected salary range', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], max_length=20),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='id_number',
            field=models.CharField(blank=True, help_text='National ID / Passport Number', max_length=50),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='languages',
            field=models.JSONField(default=list, help_text='Languages: [{"language": "...", "proficiency": "Native/Fluent/Intermediate/Basic"}]'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], max_length=20),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='notice_period',
            field=models.CharField(blank=True, help_text='Notice period (e.g., "2 weeks", "1 month")', max_length=50),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='portfolio_url',
            field=models.URLField(blank=True, help_text='Portfolio / Personal website URL'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='references',
            field=models.JSONField(default=list, help_text='References: [{"name": "...", "position": "...", "company": "...", "email": "...", "phone": "..."}]'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='state_province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='cover_letter',
            field=models.TextField(blank=True, help_text='Cover letter / Personal statement'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='education',
            field=models.JSONField(default=list, help_text='List of education: [{"institution": "...", "degree": "...", "field": "...", "start_year": "...", "end_year": "...", "gpa": "...", "honors": "..."}]'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='experience',
            field=models.JSONField(default=list, help_text='List of work experience: [{"company": "...", "position": "...", "start_date": "...", "end_date": "...", "current": false, "responsibilities": "...", "achievements": "..."}]'),
        ),
        migrations.AddIndex(
            model_name='applicantprofile',
            index=models.Index(fields=['phone_number'], name='applicant_p_phone_n_cab647_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantprofile',
            index=models.Index(fields=['city', 'country'], name='applicant_p_city_a193ac_idx'),
        ),
    ]
