# Generated by Django 6.0.1 on 2026-03-02 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_remove_application_profile_snapshot_applicationdata'),
        ('jobs', '0002_country_educationlevel_delete_certification'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='applicationdata',
            name='application_phone_n_e93d28_idx',
        ),
        migrations.RenameIndex(
            model_name='applicantprofile',
            new_name='applicant_p_city_4867b8_idx',
            old_name='applicant_p_city_a193ac_idx',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='behance_url',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='dribbble_url',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='emergency_contact_email',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='emergency_contact_relationship',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='medium_url',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='references',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='stackoverflow_url',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='twitter_url',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='citizenship',
            field=models.ForeignKey(blank=True, help_text='Citizenship / Nationality — D365 sends ISO-3 (e.g. ZWE)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citizens', to='jobs.country'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='current_job_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='education_level',
            field=models.ForeignKey(blank=True, help_text='Highest education level (must match D365 HcmEducationLevel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant_profiles', to='jobs.educationlevel'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='d365_applicant_id',
            field=models.CharField(blank=True, help_text='POSB-AI-XXXXX assigned by our system for D365', max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='d365_applicant_rec_id',
            field=models.BigIntegerField(blank=True, help_text='D365 HcmApplicant RecId', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='d365_application_rec_id',
            field=models.BigIntegerField(blank=True, help_text='D365 HRMApplication RecId', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='d365_push_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='d365_push_error',
            field=models.TextField(blank=True, help_text='Error message from last D365 push attempt'),
        ),
        migrations.AddField(
            model_name='application',
            name='d365_push_status',
            field=models.CharField(choices=[('NOT_PUSHED', 'Not Pushed'), ('PENDING', 'Pending'), ('PUSHED', 'Pushed'), ('DUPLICATE', 'Duplicate (Existing Applicant)'), ('FAILED', 'Failed')], default='NOT_PUSHED', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='d365_pushed_at',
            field=models.DateTimeField(blank=True, help_text='When this application was pushed to D365', null=True),
        ),
        migrations.AddField(
            model_name='applicationdata',
            name='citizenship',
            field=models.CharField(blank=True, help_text='ISO-3 country code e.g. ZWE', max_length=10),
        ),
        migrations.AddField(
            model_name='applicationdata',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicationdata',
            name='country',
            field=models.CharField(blank=True, help_text='ISO-2 or ISO-3 country code', max_length=10),
        ),
        migrations.AddField(
            model_name='applicationdata',
            name='current_job_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='applicationdata',
            name='education_level',
            field=models.CharField(blank=True, help_text='Must match D365 HcmEducationLevel', max_length=255),
        ),
        migrations.AddField(
            model_name='applicationdata',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='applicationdata',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='applicationdata',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='applicationdata',
            name='marital_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='applicationdata',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='applicationdata',
            name='street_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='applicationdata',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='availability_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunSQL(
            sql=[
                "ALTER TABLE applicant_profiles ALTER COLUMN country DROP NOT NULL;",
                "UPDATE applicant_profiles SET country = NULL;",
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Country of residence — D365 sends ISO-2 (e.g. ZW)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='jobs.country'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='cover_letter',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='current_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='education',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='expected_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='experience',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=20),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='notice_period',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='professional_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='applicationdata',
            name='education',
            field=models.JSONField(default=list, help_text='Detailed education entries'),
        ),
        migrations.AlterField(
            model_name='applicationdata',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='applicationdata',
            name='experience',
            field=models.JSONField(default=list, help_text='Detailed work experience entries'),
        ),
        migrations.RemoveField(
            model_name='applicationdata',
            name='address',
        ),
    ]
