# Generated by Django 6.0.1 on 2026-03-04 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_remove_applicationdata_application_phone_n_e93d28_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantprofile',
            name='availability_date',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='current_salary',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='expected_salary',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='notice_period',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='portfolio_url',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='applicationdata',
            name='education',
        ),
        migrations.RemoveField(
            model_name='applicationdata',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='applicationdata',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='applicationdata',
            name='skills',
        ),
    ]
