# Generated by Django 4.2.7 on 2026-01-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_remove_applicantprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='professional_summary',
            field=models.TextField(blank=True, help_text='Professional summary / About yourself'),
        ),
    ]
