# Generated by Django 6.0.1 on 2026-03-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_remove_applicantprofile_availability_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdata',
            name='external_application_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicationdata',
            name='file_bytes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationdata',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
