# Generated by Django 4.2.7 on 2026-01-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_applicantprofile_professional_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook profile URL'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub profile URL'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='projects',
            field=models.JSONField(blank=True, default=list, help_text='List of projects: [{"name": "...", "description": "...", "technologies": "...", "url": "...", "start_date": "...", "end_date": "...", "current": false}]'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Twitter/X profile URL'),
        ),
    ]
