# Generated by Django 4.2.7 on 2026-01-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_applicantprofile_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='behance_url',
            field=models.URLField(blank=True, help_text='Behance portfolio URL'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='dribbble_url',
            field=models.URLField(blank=True, help_text='Dribbble portfolio URL'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='medium_url',
            field=models.URLField(blank=True, help_text='Medium profile URL'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='stackoverflow_url',
            field=models.URLField(blank=True, help_text='Stack Overflow profile URL'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube channel URL'),
        ),
    ]
