# Generated by Django 4.2.7 on 2026-01-14 07:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_applicantprofile_behance_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantProfileDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CV', 'Curriculum Vitae / Resume'), ('BACHELORS_DEGREE', "Bachelor's Degree Certificate"), ('MASTERS_DEGREE', "Master's Degree Certificate"), ('DOCTORATE_DEGREE', 'Doctorate Degree Certificate'), ('DIPLOMA', 'Diploma Certificate'), ('TRANSCRIPT', 'Academic Transcript'), ('CERTIFICATE', 'Professional Certificate'), ('COVER_LETTER', 'Cover Letter'), ('ID_COPY', 'ID Copy / Passport'), ('REFERENCE_LETTER', 'Reference Letter'), ('PORTFOLIO', 'Portfolio'), ('OTHER', 'Other')], default='CV', max_length=50)),
                ('file', models.FileField(upload_to='applicant_documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('description', models.CharField(blank=True, help_text='Optional description', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('applicant_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.applicantprofile')),
            ],
            options={
                'verbose_name': 'Applicant Profile Document',
                'verbose_name_plural': 'Applicant Profile Documents',
                'db_table': 'applicant_profile_documents',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['applicant_profile', 'document_type'], name='applicant_p_applica_928f83_idx')],
            },
        ),
    ]
