# Generated by Django 6.0.1 on 2026-01-24 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'db_table': 'certifications',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'db_table': 'skills',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruiting_id', models.CharField(max_length=255, unique=True)),
                ('job_id', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.TextField(max_length=4000)),
                ('skills', models.TextField(blank=True, max_length=4000)),
                ('certificates', models.TextField(blank=True, max_length=4000)),
                ('education', models.TextField(blank=True, max_length=4000)),
                ('job_tasks', models.TextField(blank=True, max_length=4000)),
                ('responsibilities', models.TextField(blank=True, max_length=4000)),
                ('years_of_experience', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('location', models.CharField(blank=True, max_length=255)),
                ('job_type', models.CharField(blank=True, max_length=255)),
                ('job_function', models.CharField(blank=True, max_length=255)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', help_text='Current status of the job advert', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Advert',
                'verbose_name_plural': 'Job Adverts',
                'db_table': 'job_adverts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'end_date'], name='job_adverts_status_34d31c_idx'), models.Index(fields=['job_function'], name='job_adverts_job_fun_fd5e17_idx'), models.Index(fields=['created_at'], name='job_adverts_created_0fc0bf_idx')],
            },
        ),
    ]
