# Generated by Django 4.2.7 on 2026-01-13 08:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Category',
                'verbose_name_plural': 'Job Categories',
                'db_table': 'job_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'db_table': 'skills',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(help_text='Full job description')),
                ('responsibilities', models.TextField(help_text='Key responsibilities and duties')),
                ('application_deadline', models.DateTimeField(help_text='Deadline for accepting applications')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('CLOSED', 'Closed')], default='DRAFT', help_text='Current status of the job advert', max_length=20)),
                ('shortlist_count', models.IntegerField(default=10, help_text='Number of candidates to shortlist', validators=[django.core.validators.MinValueValidator(1)])),
                ('ai_shortlisting_instructions', models.TextField(blank=True, help_text='Custom instructions for AI shortlisting algorithm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_adverts', to='jobs.jobcategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_job_adverts', to=settings.AUTH_USER_MODEL)),
                ('required_skills', models.ManyToManyField(blank=True, help_text='Skills required for this position', related_name='job_adverts', to='jobs.skill')),
            ],
            options={
                'verbose_name': 'Job Advert',
                'verbose_name_plural': 'Job Adverts',
                'db_table': 'job_adverts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'application_deadline'], name='job_adverts_status_c44eca_idx'), models.Index(fields=['category'], name='job_adverts_categor_ce68b0_idx'), models.Index(fields=['created_at'], name='job_adverts_created_0fc0bf_idx')],
            },
        ),
    ]
