# Generated by Django 6.0.1 on 2026-03-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('iso2', models.CharField(help_text='ISO 3166-1 alpha-2 (e.g. ZW)', max_length=2, unique=True)),
                ('iso3', models.CharField(help_text='ISO 3166-1 alpha-3 (e.g. ZWE)', max_length=3, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Lower = higher in dropdown. Use 0 for commonly used countries.')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'countries',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Must match D365 HcmEducationLevel description', max_length=255, unique=True)),
                ('d365_code', models.CharField(blank=True, help_text='D365 education level ID/code', max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Education Level',
                'verbose_name_plural': 'Education Levels',
                'db_table': 'education_levels',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='Certification',
        ),
    ]
