# Generated by Django 6.0.1 on 2026-01-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobadvert',
            name='contract_type',
            field=models.CharField(choices=[('PERMANENT', 'Permanent'), ('FIXED_TERM', 'Fixed-Term'), ('INTERNSHIP', 'Internship'), ('PART_TIME', 'Part-Time'), ('CASUAL', 'Casual')], default='PERMANENT', help_text='Type of employment contract', max_length=20),
        ),
        migrations.AddField(
            model_name='jobadvert',
            name='education_level',
            field=models.CharField(blank=True, choices=[('DEGREE', 'Degree'), ('DIPLOMA', 'Diploma'), ('CERTIFICATION', 'Certification'), ('HIGH_SCHOOL', 'High School'), ('NONE', 'No Specific Requirement')], help_text='Minimum education level required', max_length=20),
        ),
        migrations.AddField(
            model_name='jobadvert',
            name='experience_required',
            field=models.TextField(blank=True, help_text='Experience requirements (e.g., "2 years in banking", "5 years customer service")'),
        ),
        migrations.AddField(
            model_name='jobadvert',
            name='location',
            field=models.CharField(blank=True, help_text='Specific location (branch name, city, or "Remote" for remote positions)', max_length=200),
        ),
        migrations.AddField(
            model_name='jobadvert',
            name='location_type',
            field=models.CharField(choices=[('BRANCH', 'Branch'), ('CITY', 'City'), ('REMOTE', 'Remote'), ('HYBRID', 'Hybrid')], default='BRANCH', help_text='Type of work location', max_length=20),
        ),
    ]
