# Generated by Django 4.2.7 on 2026-01-13 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortlistingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('AUTOMATIC', 'Automatic (after deadline)'), ('MANUAL', 'Manual (HR triggered)')], default='AUTOMATIC', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('shortlist_count', models.IntegerField(help_text='Number of candidates to shortlist (snapshot at time of run)')),
                ('total_applications', models.IntegerField(default=0, help_text='Total applications processed')),
                ('shortlisted_count', models.IntegerField(default=0, help_text='Number of candidates actually shortlisted')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if failed')),
                ('ai_model_version', models.CharField(blank=True, help_text='Version/identifier of AI model used', max_length=50)),
                ('ai_configuration', models.JSONField(blank=True, default=dict, help_text='AI configuration parameters used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisting_runs', to='jobs.jobadvert')),
                ('triggered_by', models.ForeignKey(help_text='User who triggered the shortlisting (null if automatic)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_shortlisting_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shortlisting Run',
                'verbose_name_plural': 'Shortlisting Runs',
                'db_table': 'shortlisting_runs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job_advert', 'status'], name='shortlistin_job_adv_e44778_idx'), models.Index(fields=['status', 'created_at'], name='shortlistin_status_0cd61e_idx')],
            },
        ),
    ]
