# Generated by Django 4.2.7 on 2026-01-13 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_hr_staff',
            field=models.BooleanField(default=False, help_text='DEPRECATED: Use user_type instead. Designates whether this user is POSB HR staff.'),
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, help_text='POSB employee ID', max_length=50, null=True, unique=True)),
                ('department', models.CharField(blank=True, help_text='Department/Division', max_length=200)),
                ('position', models.CharField(blank=True, help_text='Job title/position', max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('office_location', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('education', models.JSONField(default=list, help_text='List of education entries: [{"institution": "...", "degree": "...", "year": "..."}]')),
                ('internal_experience', models.JSONField(default=list, help_text='List of POSB work experience: [{"department": "...", "position": "...", "duration": "..."}]')),
                ('additional_info', models.JSONField(blank=True, default=dict, help_text='Additional flexible information as JSON')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this employee is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skills', models.ManyToManyField(blank=True, related_name='employee_profiles', to='jobs.skill')),
                ('user', models.OneToOneField(help_text='User account (must be employee type)', limit_choices_to={'user_type': 'EMPLOYEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Profile',
                'verbose_name_plural': 'Employee Profiles',
                'db_table': 'employee_profiles',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['employee_id'], name='employee_pr_employe_df7e0f_idx'), models.Index(fields=['is_active'], name='employee_pr_is_acti_4e40ad_idx')],
            },
        ),
    ]
