# Generated by Django 4.2.7 on 2026-01-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_refactor_employee_profile'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employeeprofile',
            name='employee_pr_employe_df7e0f_idx',
        ),
        migrations.RemoveIndex(
            model_name='employeeprofile',
            name='employee_pr_is_acti_4e40ad_idx',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='internal_experience',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='office_location',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='position',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='ec_number',
            field=models.CharField(blank=True, help_text='Employee Code (EC) Number', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('APPLICANT', 'Applicant'), ('EMPLOYEE', 'Employee')], default='APPLICANT', help_text='Type of user: Applicant (self-registered) or Employee (created by admin)', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number', max_length=20),
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['ec_number'], name='employee_pr_ec_numb_173b98_idx'),
        ),
    ]
