# Generated by Django 4.2.7 on 2026-01-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_employeeprofile_employee_pr_employe_df7e0f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='department',
            field=models.CharField(blank=True, help_text='Department/Division', max_length=200),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='job_title',
            field=models.CharField(blank=True, help_text='Job title/position', max_length=200),
        ),
    ]
