# Generated by Django 6.0.1 on 2026-01-24 21:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(choices=[('USER', 'User'), ('SYSTEM', 'System'), ('ADMIN', 'Admin')], default='USER', max_length=20)),
                ('action', models.CharField(choices=[('USER_REGISTRATION', 'User Registration'), ('OTP_VERIFICATION', 'OTP Verification'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('JOB_CREATED', 'Job Created'), ('JOB_UPDATED', 'Job Updated'), ('JOB_DELETED', 'Job Deleted'), ('APPLICATION_SUBMITTED', 'Application Submitted'), ('APPLICATION_UPDATED', 'Application Updated'), ('AI_SHORTLISTING', 'AI Shortlisting'), ('EMAIL_SENT', 'Email Sent'), ('ERP_EXPORT', 'ERP Export'), ('PROFILE_UPDATED', 'Profile Updated'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('PASSWORD_CHANGED', 'Password Changed')], max_length=50)),
                ('action_description', models.TextField(help_text='Human-readable description of the action')),
                ('entity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context data (IP address, user agent, etc.)')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action (null if system)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('entity_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['actor', 'timestamp'], name='audit_logs_actor_i_ce2144_idx'), models.Index(fields=['action', 'timestamp'], name='audit_logs_action_474804_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_logs_entity__b12121_idx'), models.Index(fields=['timestamp'], name='audit_logs_timesta_423be6_idx')],
            },
        ),
    ]
