# Generated by Django 6.0.1 on 2026-01-24 21:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10)),
                ('source', models.CharField(choices=[('API', 'API'), ('CELERY', 'Celery Task'), ('INTEGRATION', 'External Integration'), ('SYSTEM', 'System')], default='SYSTEM', max_length=20)),
                ('message', models.TextField(help_text='Log message')),
                ('stack_trace', models.TextField(blank=True, help_text='Stack trace if error occurred')),
                ('module', models.CharField(blank=True, help_text='Module/component where log originated', max_length=200)),
                ('function', models.CharField(blank=True, help_text='Function/method where log originated', max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context data')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Log',
                'verbose_name_plural': 'System Logs',
                'db_table': 'system_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['level', 'timestamp'], name='system_logs_level_36b166_idx'), models.Index(fields=['source', 'timestamp'], name='system_logs_source_071e9d_idx'), models.Index(fields=['timestamp'], name='system_logs_timesta_84e60c_idx')],
            },
        ),
    ]
