# Generated by Django 6.0.1 on 2026-01-24 21:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('jobs', '0001_initial'),
        ('shortlisting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this API key', max_length=255)),
                ('key', models.CharField(help_text='The actual API key value', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this key is currently active')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time this key was used', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this key', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'db_table': 'api_keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')], max_length=10)),
                ('endpoint', models.CharField(help_text='API endpoint path', max_length=255)),
                ('request_body', models.TextField(blank=True, help_text='Request payload (truncated if too long)')),
                ('request_headers', models.JSONField(blank=True, default=dict, help_text='Request headers (excluding sensitive data)')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='User agent string', max_length=500)),
                ('status_code', models.IntegerField(help_text='HTTP status code')),
                ('response_status', models.CharField(choices=[('SUCCESS', 'Success'), ('ERROR', 'Error'), ('VALIDATION_ERROR', 'Validation Error'), ('UNAUTHORIZED', 'Unauthorized'), ('RATE_LIMITED', 'Rate Limited'), ('NOT_FOUND', 'Not Found'), ('SERVER_ERROR', 'Server Error')], help_text='Response status category', max_length=50)),
                ('response_body', models.TextField(blank=True, help_text='Response payload (truncated if too long)')),
                ('error_message', models.TextField(blank=True, help_text='Error message if request failed')),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context data')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('api_key', models.ForeignKey(blank=True, help_text='API key used for this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to='integrations.apikey')),
            ],
            options={
                'verbose_name': 'API Request Log',
                'verbose_name_plural': 'API Request Logs',
                'db_table': 'api_request_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ERPExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('total_candidates', models.IntegerField(default=0)),
                ('exported_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('erp_batch_id', models.CharField(blank=True, max_length=255)),
                ('erp_response', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_retries', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_exports', to='jobs.jobadvert')),
                ('shortlisting_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_exports', to='shortlisting.shortlistingrun')),
            ],
            options={
                'verbose_name': 'ERP Export',
                'verbose_name_plural': 'ERP Exports',
                'db_table': 'erp_exports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ERPExportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('EXPORTED', 'Exported'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('erp_candidate_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_export_items', to='applications.application')),
                ('export', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='integrations.erpexport')),
            ],
            options={
                'verbose_name': 'ERP Export Item',
                'verbose_name_plural': 'ERP Export Items',
                'db_table': 'erp_export_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['key', 'is_active'], name='api_keys_key_9cfb4a_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['is_active'], name='api_keys_is_acti_73be43_idx'),
        ),
        migrations.AddIndex(
            model_name='apirequestlog',
            index=models.Index(fields=['api_key', 'timestamp'], name='api_request_api_key_a1dc86_idx'),
        ),
        migrations.AddIndex(
            model_name='apirequestlog',
            index=models.Index(fields=['status_code', 'timestamp'], name='api_request_status__ac6ed4_idx'),
        ),
        migrations.AddIndex(
            model_name='apirequestlog',
            index=models.Index(fields=['response_status', 'timestamp'], name='api_request_respons_649da6_idx'),
        ),
        migrations.AddIndex(
            model_name='apirequestlog',
            index=models.Index(fields=['timestamp'], name='api_request_timesta_daf0c8_idx'),
        ),
        migrations.AddIndex(
            model_name='apirequestlog',
            index=models.Index(fields=['endpoint', 'timestamp'], name='api_request_endpoin_e13d35_idx'),
        ),
        migrations.AddIndex(
            model_name='erpexport',
            index=models.Index(fields=['status', 'created_at'], name='erp_exports_status_d465d3_idx'),
        ),
        migrations.AddIndex(
            model_name='erpexportitem',
            index=models.Index(fields=['status', 'created_at'], name='erp_export__status_68914d_idx'),
        ),
    ]
