# Generated by Django 4.2.7 on 2026-01-13 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('jobs', '0001_initial'),
        ('shortlisting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERPExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial Success')], default='PENDING', max_length=20)),
                ('total_candidates', models.IntegerField(default=0)),
                ('exported_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('erp_batch_id', models.CharField(blank=True, help_text='Batch ID returned by Dynamics 365', max_length=255)),
                ('erp_response', models.JSONField(blank=True, default=dict, help_text='Full response from Dynamics 365 API')),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_exports', to='jobs.jobadvert')),
                ('shortlisting_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_exports', to='shortlisting.shortlistingrun')),
            ],
            options={
                'verbose_name': 'ERP Export',
                'verbose_name_plural': 'ERP Exports',
                'db_table': 'erp_exports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ERPExportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('EXPORTED', 'Exported'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('erp_candidate_id', models.CharField(blank=True, help_text='Candidate ID in Dynamics 365', max_length=255)),
                ('erp_document_id', models.CharField(blank=True, help_text='Document ID in Dynamics 365', max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_export_items', to='applications.application')),
                ('export', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_items', to='integrations.erpexport')),
            ],
            options={
                'verbose_name': 'ERP Export Item',
                'verbose_name_plural': 'ERP Export Items',
                'db_table': 'erp_export_items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['export', 'status'], name='erp_export__export__8225a1_idx'), models.Index(fields=['status', 'created_at'], name='erp_export__status_68914d_idx')],
                'unique_together': {('export', 'application')},
            },
        ),
        migrations.AddIndex(
            model_name='erpexport',
            index=models.Index(fields=['status', 'created_at'], name='erp_exports_status_d465d3_idx'),
        ),
        migrations.AddIndex(
            model_name='erpexport',
            index=models.Index(fields=['job_advert', 'status'], name='erp_exports_job_adv_69b1ca_idx'),
        ),
    ]
