"""
Management command to seed ALL countries with ISO-2 and ISO-3 codes.
Zimbabwe is prioritized at the top of dropdowns.

Usage: python manage.py seed_countries
"""
from django.core.management.base import BaseCommand
from jobs.models import Country


COUNTRIES = [
    # sort_order 0 = Zimbabwe (home country, always first)
    ("Zimbabwe", "ZW", "ZWE", 0),
    # sort_order 1 = SADC neighbours
    ("South Africa", "ZA", "ZAF", 1),
    ("Botswana", "BW", "BWA", 1),
    ("Zambia", "ZM", "ZMB", 1),
    ("Mozambique", "MZ", "MOZ", 1),
    ("Malawi", "MW", "MWI", 1),
    ("Namibia", "NA", "NAM", 1),
    ("Tanzania", "TZ", "TZA", 1),
    ("Eswatini", "SZ", "SWZ", 1),
    ("Lesotho", "LS", "LSO", 1),
    ("Democratic Republic of the Congo", "CD", "COD", 1),
    # sort_order 10 = all remaining countries alphabetically
    ("Afghanistan", "AF", "AFG", 10),
    ("Albania", "AL", "ALB", 10),
    ("Algeria", "DZ", "DZA", 10),
    ("Andorra", "AD", "AND", 10),
    ("Angola", "AO", "AGO", 10),
    ("Antigua and Barbuda", "AG", "ATG", 10),
    ("Argentina", "AR", "ARG", 10),
    ("Armenia", "AM", "ARM", 10),
    ("Australia", "AU", "AUS", 10),
    ("Austria", "AT", "AUT", 10),
    ("Azerbaijan", "AZ", "AZE", 10),
    ("Bahamas", "BS", "BHS", 10),
    ("Bahrain", "BH", "BHR", 10),
    ("Bangladesh", "BD", "BGD", 10),
    ("Barbados", "BB", "BRB", 10),
    ("Belarus", "BY", "BLR", 10),
    ("Belgium", "BE", "BEL", 10),
    ("Belize", "BZ", "BLZ", 10),
    ("Benin", "BJ", "BEN", 10),
    ("Bhutan", "BT", "BTN", 10),
    ("Bolivia", "BO", "BOL", 10),
    ("Bosnia and Herzegovina", "BA", "BIH", 10),
    ("Brazil", "BR", "BRA", 10),
    ("Brunei", "BN", "BRN", 10),
    ("Bulgaria", "BG", "BGR", 10),
    ("Burkina Faso", "BF", "BFA", 10),
    ("Burundi", "BI", "BDI", 10),
    ("Cabo Verde", "CV", "CPV", 10),
    ("Cambodia", "KH", "KHM", 10),
    ("Cameroon", "CM", "CMR", 10),
    ("Canada", "CA", "CAN", 10),
    ("Central African Republic", "CF", "CAF", 10),
    ("Chad", "TD", "TCD", 10),
    ("Chile", "CL", "CHL", 10),
    ("China", "CN", "CHN", 10),
    ("Colombia", "CO", "COL", 10),
    ("Comoros", "KM", "COM", 10),
    ("Congo", "CG", "COG", 10),
    ("Costa Rica", "CR", "CRI", 10),
    ("Cote d'Ivoire", "CI", "CIV", 10),
    ("Croatia", "HR", "HRV", 10),
    ("Cuba", "CU", "CUB", 10),
    ("Cyprus", "CY", "CYP", 10),
    ("Czech Republic", "CZ", "CZE", 10),
    ("Denmark", "DK", "DNK", 10),
    ("Djibouti", "DJ", "DJI", 10),
    ("Dominica", "DM", "DMA", 10),
    ("Dominican Republic", "DO", "DOM", 10),
    ("Ecuador", "EC", "ECU", 10),
    ("Egypt", "EG", "EGY", 10),
    ("El Salvador", "SV", "SLV", 10),
    ("Equatorial Guinea", "GQ", "GNQ", 10),
    ("Eritrea", "ER", "ERI", 10),
    ("Estonia", "EE", "EST", 10),
    ("Ethiopia", "ET", "ETH", 10),
    ("Fiji", "FJ", "FJI", 10),
    ("Finland", "FI", "FIN", 10),
    ("France", "FR", "FRA", 10),
    ("Gabon", "GA", "GAB", 10),
    ("Gambia", "GM", "GMB", 10),
    ("Georgia", "GE", "GEO", 10),
    ("Germany", "DE", "DEU", 10),
    ("Ghana", "GH", "GHA", 10),
    ("Greece", "GR", "GRC", 10),
    ("Grenada", "GD", "GRD", 10),
    ("Guatemala", "GT", "GTM", 10),
    ("Guinea", "GN", "GIN", 10),
    ("Guinea-Bissau", "GW", "GNB", 10),
    ("Guyana", "GY", "GUY", 10),
    ("Haiti", "HT", "HTI", 10),
    ("Honduras", "HN", "HND", 10),
    ("Hungary", "HU", "HUN", 10),
    ("Iceland", "IS", "ISL", 10),
    ("India", "IN", "IND", 10),
    ("Indonesia", "ID", "IDN", 10),
    ("Iran", "IR", "IRN", 10),
    ("Iraq", "IQ", "IRQ", 10),
    ("Ireland", "IE", "IRL", 10),
    ("Israel", "IL", "ISR", 10),
    ("Italy", "IT", "ITA", 10),
    ("Jamaica", "JM", "JAM", 10),
    ("Japan", "JP", "JPN", 10),
    ("Jordan", "JO", "JOR", 10),
    ("Kazakhstan", "KZ", "KAZ", 10),
    ("Kenya", "KE", "KEN", 10),
    ("Kiribati", "KI", "KIR", 10),
    ("Kosovo", "XK", "XKX", 10),
    ("Kuwait", "KW", "KWT", 10),
    ("Kyrgyzstan", "KG", "KGZ", 10),
    ("Laos", "LA", "LAO", 10),
    ("Latvia", "LV", "LVA", 10),
    ("Lebanon", "LB", "LBN", 10),
    ("Liberia", "LR", "LBR", 10),
    ("Libya", "LY", "LBY", 10),
    ("Liechtenstein", "LI", "LIE", 10),
    ("Lithuania", "LT", "LTU", 10),
    ("Luxembourg", "LU", "LUX", 10),
    ("Madagascar", "MG", "MDG", 10),
    ("Malaysia", "MY", "MYS", 10),
    ("Maldives", "MV", "MDV", 10),
    ("Mali", "ML", "MLI", 10),
    ("Malta", "MT", "MLT", 10),
    ("Marshall Islands", "MH", "MHL", 10),
    ("Mauritania", "MR", "MRT", 10),
    ("Mauritius", "MU", "MUS", 10),
    ("Mexico", "MX", "MEX", 10),
    ("Micronesia", "FM", "FSM", 10),
    ("Moldova", "MD", "MDA", 10),
    ("Monaco", "MC", "MCO", 10),
    ("Mongolia", "MN", "MNG", 10),
    ("Montenegro", "ME", "MNE", 10),
    ("Morocco", "MA", "MAR", 10),
    ("Myanmar", "MM", "MMR", 10),
    ("Nauru", "NR", "NRU", 10),
    ("Nepal", "NP", "NPL", 10),
    ("Netherlands", "NL", "NLD", 10),
    ("New Zealand", "NZ", "NZL", 10),
    ("Nicaragua", "NI", "NIC", 10),
    ("Niger", "NE", "NER", 10),
    ("Nigeria", "NG", "NGA", 10),
    ("North Korea", "KP", "PRK", 10),
    ("North Macedonia", "MK", "MKD", 10),
    ("Norway", "NO", "NOR", 10),
    ("Oman", "OM", "OMN", 10),
    ("Pakistan", "PK", "PAK", 10),
    ("Palau", "PW", "PLW", 10),
    ("Palestine", "PS", "PSE", 10),
    ("Panama", "PA", "PAN", 10),
    ("Papua New Guinea", "PG", "PNG", 10),
    ("Paraguay", "PY", "PRY", 10),
    ("Peru", "PE", "PER", 10),
    ("Philippines", "PH", "PHL", 10),
    ("Poland", "PL", "POL", 10),
    ("Portugal", "PT", "PRT", 10),
    ("Qatar", "QA", "QAT", 10),
    ("Romania", "RO", "ROU", 10),
    ("Russia", "RU", "RUS", 10),
    ("Rwanda", "RW", "RWA", 10),
    ("Saint Kitts and Nevis", "KN", "KNA", 10),
    ("Saint Lucia", "LC", "LCA", 10),
    ("Saint Vincent and the Grenadines", "VC", "VCT", 10),
    ("Samoa", "WS", "WSM", 10),
    ("San Marino", "SM", "SMR", 10),
    ("Sao Tome and Principe", "ST", "STP", 10),
    ("Saudi Arabia", "SA", "SAU", 10),
    ("Senegal", "SN", "SEN", 10),
    ("Serbia", "RS", "SRB", 10),
    ("Seychelles", "SC", "SYC", 10),
    ("Sierra Leone", "SL", "SLE", 10),
    ("Singapore", "SG", "SGP", 10),
    ("Slovakia", "SK", "SVK", 10),
    ("Slovenia", "SI", "SVN", 10),
    ("Solomon Islands", "SB", "SLB", 10),
    ("Somalia", "SO", "SOM", 10),
    ("South Korea", "KR", "KOR", 10),
    ("South Sudan", "SS", "SSD", 10),
    ("Spain", "ES", "ESP", 10),
    ("Sri Lanka", "LK", "LKA", 10),
    ("Sudan", "SD", "SDN", 10),
    ("Suriname", "SR", "SUR", 10),
    ("Sweden", "SE", "SWE", 10),
    ("Switzerland", "CH", "CHE", 10),
    ("Syria", "SY", "SYR", 10),
    ("Taiwan", "TW", "TWN", 10),
    ("Tajikistan", "TJ", "TJK", 10),
    ("Thailand", "TH", "THA", 10),
    ("Timor-Leste", "TL", "TLS", 10),
    ("Togo", "TG", "TGO", 10),
    ("Tonga", "TO", "TON", 10),
    ("Trinidad and Tobago", "TT", "TTO", 10),
    ("Tunisia", "TN", "TUN", 10),
    ("Turkey", "TR", "TUR", 10),
    ("Turkmenistan", "TM", "TKM", 10),
    ("Tuvalu", "TV", "TUV", 10),
    ("Uganda", "UG", "UGA", 10),
    ("Ukraine", "UA", "UKR", 10),
    ("United Arab Emirates", "AE", "ARE", 10),
    ("United Kingdom", "GB", "GBR", 10),
    ("United States", "US", "USA", 10),
    ("Uruguay", "UY", "URY", 10),
    ("Uzbekistan", "UZ", "UZB", 10),
    ("Vanuatu", "VU", "VUT", 10),
    ("Vatican City", "VA", "VAT", 10),
    ("Venezuela", "VE", "VEN", 10),
    ("Vietnam", "VN", "VNM", 10),
    ("Yemen", "YE", "YEM", 10),
]


class Command(BaseCommand):
    help = "Seed all countries with ISO-2 / ISO-3 codes (Zimbabwe prioritized)"

    def add_arguments(self, parser):
        parser.add_argument(
            "--clear",
            action="store_true",
            help="Clear existing countries before seeding",
        )

    def handle(self, *args, **options):
        if options["clear"]:
            self.stdout.write(self.style.WARNING("Clearing existing countries..."))
            Country.objects.all().delete()

        created = 0
        updated = 0

        for name, iso2, iso3, sort_order in COUNTRIES:
            _, was_created = Country.objects.update_or_create(
                iso2=iso2,
                defaults={
                    "name": name,
                    "iso3": iso3,
                    "sort_order": sort_order,
                    "is_active": True,
                },
            )
            if was_created:
                created += 1
            else:
                updated += 1

        self.stdout.write(self.style.SUCCESS(
            f"Done: {created} created, {updated} updated, {Country.objects.count()} total countries."
        ))
